Repository jenkinsci/forensics-api-plugin, pull requests merged in 2020-08, with the labels that each got.

#199 Remove AsciiDoc generation from build
  etc/PluginGuide.adoc
  etc/images/build.png
  etc/images/card.png
  etc/images/font-awesome.png
  etc/images/grid.png
  etc/images/job.png
  etc/images/jobs.png
  etc/images/pie.png
  etc/images/table.png
  etc/images/trend-lines.png
  etc/images/trend-stacked.png
  pom.xml
Labels: documentation

#198 [JENKINS-60931] Improve repository miner with an incremental analysis
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMiner.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMinerStep.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryStatistics.java
  src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java
Labels: enhancement

#203 Bump version of analysis pom to 4.1.0
  Jenkinsfile
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/forensics/blame/FileBlame.java
  src/main/java/io/jenkins/plugins/forensics/miner/ForensicsJobAction.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMiner.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMinerStep.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryStatistics.java
  src/main/resources/io/jenkins/plugins/forensics/miner/Messages.properties
  src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java
Labels: internal

#202 Add `readResolve` to correctly serialize existing instances
  Jenkinsfile
  README.md
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMiner.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryMinerStep.java
  src/main/java/io/jenkins/plugins/forensics/miner/RepositoryStatistics.java
  src/main/resources/io/jenkins/plugins/forensics/miner/Messages.properties
  src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java
Labels: internal

#205 Add API to find reference builds
  .github/dependabot.yml
  README.md
  codacy/checkstyle.xml
  etc/assertj-templates/has_assertion_template.txt
  pom.xml
  src/main/java/io/jenkins/plugins/forensics/blame/BlamerFactory.java
  src/main/java/io/jenkins/plugins/forensics/miner/MinerFactory.java
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceBuild.java
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceJobModelValidation.java
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
  src/main/resources/io/jenkins/plugins/forensics/reference/Messages.properties
  src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.jelly
  src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.properties
  src/main/webapp/icons/crosshair-24x24.png
  src/main/webapp/icons/crosshair-48x48.png
  src/test/java/io/jenkins/plugins/forensics/blame/BlamerFactoryITest.java
  src/test/java/io/jenkins/plugins/forensics/miner/MinerFactoryITest.java
  src/test/java/io/jenkins/plugins/forensics/reference/ReferenceBuildTest.java
  src/test/java/io/jenkins/plugins/forensics/reference/ReferenceJobModelValidationTest.java
  src/test/resources/design.puml
Labels: feature
