Repository jenkinsci/forensics-api-plugin, pull requests merged in 2021-11, with the labels that each got.

#352 Add a unit test for `RelativeCountCommitStatisticsSeriesBuilder`
  src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountCommitStatisticsSeriesBuilderTest.java
Labels: tests

#356 Add unit test for `CodeMetricTrendChart`
  src/test/java/io/jenkins/plugins/forensics/miner/CodeMetricTrendChartTest.java
Labels: tests

#351 Add unit test for `AddedVersusDeletedLinesTrendChart`
  src/test/java/io/jenkins/plugins/forensics/miner/AddedVersusDeletedLinesTrendChartTest.java
Labels: tests

#355 Add test for `RelativeCountTrendChartTest`
  src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
Labels: tests

#361 The initial setting of default branch should be empty
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
  src/test/java/io/jenkins/plugins/forensics/reference/ReferenceRecorderTest.java
Labels: bug

#359 Improve API by providing an additional logger in `find`.
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
  src/test/java/io/jenkins/plugins/forensics/reference/ReferenceRecorderTest.java
Labels: internal

#365 Add a new detail view that shows info and error messages
  pom.xml
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceBuild.java
  src/main/java/io/jenkins/plugins/forensics/reference/ReferenceRecorder.java
  src/main/resources/io/jenkins/plugins/forensics/reference/Messages.properties
  src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.jelly
  src/main/resources/io/jenkins/plugins/forensics/reference/ReferenceBuild/summary.properties
  src/test/java/io/jenkins/plugins/forensics/reference/ReferenceBuildTest.java
Labels: enhancement

#369 [JENKINS-66878] Unit test for CommitStatisticsJobAction
  src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsJobActionTest.java
Labels: tests
